// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz5JSv8rAoiugJg7BSpeNG51whMT9GgLo',
    appId: '1:535979793677:android:493deffdab6e8590296444',
    messagingSenderId: '535979793677',
    projectId: 'chatup-77988',
    storageBucket: 'chatup-77988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo2rk1qTl4_pZNrbZUnLCiva9hu8LhYAY',
    appId: '1:535979793677:ios:8e5b28ca4dcdf2c8296444',
    messagingSenderId: '535979793677',
    projectId: 'chatup-77988',
    storageBucket: 'chatup-77988.appspot.com',
    androidClientId: '535979793677-545ucj9ira68ubh47tmrnoir32q7q0df.apps.googleusercontent.com',
    iosClientId: '535979793677-de09p0kmunbuejdr6iuthcj0ke4l9riv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatus',
  );
}
